apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: cf-auth-proxy
  name: cf-auth-proxy
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: cf-auth-proxy
  template:
    metadata:
      labels:
        k8s-app: cf-auth-proxy
    spec:
      containers:
      - 
        env:
        - name: POLICY_AUD
          valueFrom:
          secretKeyRef:
            name: cf-auth-proxy
            key: policy-aud
        - name: AUTH_DOMAIN
          valueFrom:
          secretKeyRef:
            name: cf-auth-proxy
            key: auth-domain
        image: mustafakirimli/cf-auth-proxy:latest
        imagePullPolicy: Always
        name: cf-auth-proxy
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 300m
            memory: 400M
          limits:
            cpu: 500m
            memory: 600M
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: cf-auth-proxy
  name: cf-auth-proxy
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    k8s-app: cf-auth-proxy
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: kube-system
  name: cf-auth-proxy
  labels:
    app: cf-auth-proxy
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: cf-auth-proxy
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 40
