apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: cf-auth-proxy
  name: cf-auth-proxy
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: cf-auth-proxy
  template:
    metadata:
      labels:
        k8s-app: cf-auth-proxy
    spec:
      containers:
      - 
        env:
        - name: POLICY_AUD
          value: AUDEXAMPLEAUDAUDEXAMPLEAUD
        - name: AUTH_DOMAIN
          value: mydomain.cloudflareaccess.com
        image: mkirimli/cf-auth-proxy:latest
        imagePullPolicy: Always
        name: cf-auth-proxy
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 300m
            memory: 400M
          limits:
            cpu: 500m
            memory: 600M
